"""Generate OA/SKILL that recreates a connected schematic from SchematicIR."""

from __future__ import annotations

import re

from .models import DeviceMap, DeviceMapEntry, Instance, SchematicIR
from .placement import Placement, get_placements


_SCHEMATIC_SCALE = 0.01
_ENGINEERING_SUFFIXES = {
    "t": 1e12,
    "g": 1e9,
    "meg": 1e6,
    "k": 1e3,
    "m": 1e-3,
    "u": 1e-6,
    "n": 1e-9,
    "p": 1e-12,
    "f": 1e-15,
}


def write_skill(
    ir: SchematicIR,
    device_map: DeviceMap,
    lib_name: str,
    cell_name: str,
    tech_lib: str = "",
) -> str:
    """Render the feature-branch OA schematic writer as a SKILL script."""
    _validate_device_map(ir, device_map)
    placements = get_placements(ir)
    lines = [
        ";; Auto-generated by Circuit Agent OA schematic exporter",
        f";; Source subckt: {ir.subckt_name}",
        "",
        f"libObj = ddGetObj({_skill_str(lib_name)})",
        f"unless(libObj libObj = ddCreateLib({_skill_str(lib_name)}))",
    ]
    if tech_lib:
        lines.append(
            f"when(libObj techBindTechFile(libObj {_skill_str(tech_lib)}))"
        )
    lines.extend(
        [
            (
                "cv = dbOpenCellViewByType("
                f"{_skill_str(lib_name)} {_skill_str(cell_name)} "
                '"schematic" "schematic" "w")'
            ),
            'unless(cv error("failed to open target schematic"))',
            ";; Replace the previous generated cellview",
            "foreach(i cv~>instances dbDeleteObject(i))",
            "foreach(s cv~>shapes dbDeleteObject(s))",
            "foreach(l cv~>labels dbDeleteObject(l))",
            "foreach(p cv~>pins dbDeleteObject(p))",
            "foreach(t cv~>terminals dbDeleteObject(t))",
            "foreach(n cv~>nets dbDeleteObject(n))",
            "",
            ";; Create named nets",
        ]
    )
    for net in ir.nets:
        lines.append(
            f"unless(dbFindNetByName(cv {_skill_str(net)}) "
            f"dbCreateNet(cv {_skill_str(net)}))"
        )

    lines.extend(["", ";; Create instances and label their real symbol pins"])
    for instance in ir.instances:
        lines.extend(
            _instance_lines(
                instance,
                device_map[instance.model],
                placements[instance.name],
            )
        )

    lines.extend(["", ";; Create real top-level schematic pins"])
    for index, port in enumerate(ir.ports):
        lines.extend(_port_lines(port, index))

    lines.extend(
        [
            "",
            "errset(schCheck(cv) t)",
            "dbSave(cv)",
            "dbClose(cv)",
            (
                f'printf("BO schematic generated: {lib_name}/{cell_name}/schematic\\n")'
            ),
            "",
        ]
    )
    return "\n".join(lines)


def _validate_device_map(ir: SchematicIR, device_map: DeviceMap) -> None:
    missing = sorted(
        {instance.model for instance in ir.instances if instance.model not in device_map}
    )
    if missing:
        raise ValueError(
            "Device map is missing entries for models/kinds: " + ", ".join(missing)
        )
    invalid = sorted(
        {
            entry.instantiation_method
            for entry in device_map.values()
            if entry.instantiation_method
            not in {"dbCreateParamInst", "dbCreateInstByMasterName"}
        }
    )
    if invalid:
        raise ValueError(
            "Unsupported Virtuoso instantiation method(s): " + ", ".join(invalid)
        )


def _instance_lines(
    instance: Instance,
    entry: DeviceMapEntry,
    placement: Placement,
) -> list[str]:
    x = _coord(placement.x)
    y = _coord(placement.y)
    inst_id = _skill_id("inst_" + instance.name)
    mapped_params = {
        entry.param_map.get(name, name.lower()): value
        for name, value in instance.params.items()
    }
    if entry.instantiation_method == "dbCreateParamInst":
        param_list = _skill_param_inst_list(mapped_params, entry.param_types)
        lines = [
            (
                f"{inst_id} = dbCreateParamInst(cv "
                f"dbOpenCellViewByType({_skill_str(entry.lib)} {_skill_str(entry.cell)} "
                f"{_skill_str(entry.view)} nil \"r\") {_skill_str(instance.name)} "
                f"{x:g}:{y:g} {_skill_str(placement.orient)} 1 {param_list})"
            )
        ]
    else:
        lines = [
            (
                f"{inst_id} = dbCreateInstByMasterName(cv {_skill_str(entry.lib)} "
                f"{_skill_str(entry.cell)} {_skill_str(entry.view)} "
                f"{_skill_str(instance.name)} list({x:g} {y:g}) "
                f"{_skill_str(placement.orient)})"
            )
        ]
        for name, value in sorted(mapped_params.items()):
            param_type = entry.param_types.get(name) or _skill_param_type(value)
            lines.append(
                f"dbReplaceProp({inst_id} {_skill_str(name)} '{param_type} "
                f"{_skill_prop_value(_coerce_param(value, param_type))})"
            )

    term_order = _term_order(instance, entry.term_order)
    for node, terminal in zip(instance.nodes, term_order):
        lines.extend(_schematic_net_stub_lines(instance, entry, terminal, node))
    lines.append("")
    return lines


def _schematic_net_stub_lines(
    instance: Instance,
    entry: DeviceMapEntry,
    terminal: str,
    net: str,
) -> tuple[str, ...]:
    dx, dy = _terminal_stub_delta(instance, entry, terminal)
    inst_id = _skill_id("inst_" + instance.name)
    return (
        (
            f"when({inst_id} masterTerm = dbFindTermByName({inst_id}->master "
            f"{_skill_str(terminal)}) masterPin = when(masterTerm car(masterTerm~>pins)) "
            f"pinFig = when(masterPin car(masterPin~>figs)) "
            f"when(pinFig pinXY = dbTransformPoint(centerBox(pinFig~>bBox) "
            f"{inst_id}~>transform) stubXY = list(car(pinXY)+{dx:g} "
            f"cadr(pinXY)+{dy:g}) wireObjs = schCreateWire(cv \"draw\" \"full\" "
            "list(pinXY stubXY) 0.0625 0.0625 0.0) "
            f"when(wireObjs schCreateWireLabel(cv car(wireObjs) stubXY "
            f"{_skill_str(net)} \"centerLeft\" \"R0\" \"stick\" 0.125 nil))))"
        ),
    )


def _port_lines(port: str, index: int) -> tuple[str, ...]:
    direction = _port_direction(port)
    pin_cell = {"input": "ipin", "output": "opin", "inputOutput": "iopin"}[
        direction
    ]
    x0, y, x1 = _port_stub(index)
    port_id = _skill_id("port_" + port)
    wire_id = _skill_id("port_wire_" + port)
    return (
        (
            f"{port_id} = schCreatePin(cv dbOpenCellViewByType(\"basic\" "
            f"{_skill_str(pin_cell)} \"symbol\" nil \"r\") {_skill_str(port)} "
            f"{_skill_str(direction)} nil list({x0:g} {y:g}) \"R0\")"
        ),
        (
            f"{wire_id} = schCreateWire(cv \"draw\" \"full\" "
            f"list(list({x0:g} {y:g}) list({x1:g} {y:g})) 0.0625 0.0625 0.0)"
        ),
        (
            f"when({wire_id} schCreateWireLabel(cv car({wire_id}) "
            f"list({x1:g} {y:g}) {_skill_str(port)} \"centerLeft\" \"R0\" "
            '"stick" 0.125 nil))'
        ),
        f"; term {port} direction={direction} net={port}",
    )


def _skill_param_inst_list(
    params: dict[str, str],
    param_types: dict[str, str],
) -> str:
    entries: list[str] = []
    for name, value in sorted(params.items()):
        param_type = param_types.get(name) or _skill_param_type(value)
        coerced = _coerce_param(value, param_type)
        entries.append(
            f"list({_skill_str(name)} {_skill_str(param_type)} "
            f"{_skill_prop_value(coerced)})"
        )
    return "list(" + " ".join(entries) + ")"


def _coerce_param(value: object, param_type: str) -> object:
    if param_type == "int":
        return int(round(_engineering_float(value)))
    if param_type == "float":
        return _engineering_float(value)
    if param_type == "boolean":
        if isinstance(value, str):
            return value.strip().lower() in {"1", "t", "true", "yes"}
        return bool(value)
    return str(value)


def _engineering_float(value: object) -> float:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    token = str(value).strip().lower()
    match = re.fullmatch(
        r"([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)(meg|[tgkmunpf])?",
        token,
    )
    if not match:
        raise ValueError(f"Cannot convert Virtuoso parameter value {value!r}")
    return float(match.group(1)) * _ENGINEERING_SUFFIXES.get(match.group(2) or "", 1.0)


def _skill_param_type(value: object) -> str:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    return "string"


def _skill_prop_value(value: object) -> str:
    if isinstance(value, bool):
        return "t" if value else "nil"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return f"{value:.17g}"
    return _skill_str(str(value))


def _term_order(instance: Instance, configured: list[str]) -> list[str]:
    if configured:
        return configured
    return ["D", "G", "S", "B"] if instance.kind == "mos" else ["PLUS", "MINUS"]


def _terminal_stub_delta(
    instance: Instance,
    entry: DeviceMapEntry,
    terminal: str,
) -> tuple[float, float]:
    term = terminal.upper()
    is_pmos = "pch" in entry.cell.lower() or "pmos" in entry.cell.lower()
    if term == "D":
        return (0.0, -0.5 if is_pmos else 0.5)
    if term == "S":
        return (0.0, 0.5 if is_pmos else -0.5)
    if term == "G":
        return (-0.5, 0.0)
    if term == "B":
        return (0.5, 0.0)
    if term == "PLUS":
        return (-0.5, 0.0)
    return (0.5, 0.0)


def _port_direction(port: str) -> str:
    lowered = port.lower()
    if lowered in {"vout", "out"}:
        return "output"
    if lowered in {"vdd", "vss", "gnd", "gnd!", "vdd!", "vss!"}:
        return "inputOutput"
    return "input"


def _port_stub(index: int) -> tuple[float, float, float]:
    y = 5.0 - 1.25 * index
    return (-6.0, y, -4.0)


def _coord(value: float) -> float:
    return round(value * _SCHEMATIC_SCALE, 3)


def _skill_id(value: str) -> str:
    return "".join(character if character.isalnum() or character == "_" else "_" for character in value)


def _skill_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
