"""Generate SKILL scripts that recreate a schematic from SchematicIR."""

from __future__ import annotations

from datetime import datetime

from .models import DeviceMap, Instance, SchematicIR
from .placement import Placement, get_placements


def write_skill(
    ir: SchematicIR,
    device_map: DeviceMap,
    lib_name: str,
    cell_name: str,
) -> str:
    """Render a Virtuoso SKILL script for a schematic IR."""
    _validate_device_map(ir, device_map)
    placements = get_placements(ir)
    lines: list[str] = [
        ";; Auto-generated by Circuit Agent BO Virtuoso exporter",
        f";; Generated at: {datetime.now().isoformat(timespec='seconds')}",
        f";; Source subckt: {ir.subckt_name}",
        "",
        "procedure(boEnsureNet(cv name)",
        "  let((net)",
        "    net = dbFindNetByName(cv name)",
        "    unless(net net = dbCreateNet(cv name))",
        "    net",
        "  )",
        ")",
        "",
        "procedure(boReplaceProp(obj name value)",
        "  when(value",
        "    when(dbFindProp(obj name) dbDeleteObject(dbFindProp(obj name)))",
        "    dbCreateProp(obj name \"string\" value)",
        "  )",
        ")",
        "",
        "procedure(boClearCellView(cv)",
        "  foreach(inst cv~>instances dbDeleteObject(inst))",
        "  foreach(shape cv~>shapes dbDeleteObject(shape))",
        "  foreach(term cv~>terminals dbDeleteObject(term))",
        "  foreach(net cv~>nets dbDeleteObject(net))",
        ")",
        "",
        "procedure(boMaybeCreateWire(cv x1 y1 x2 y2)",
        "  ;; Visual aid only. Connectivity is created by dbCreateConnByName.",
        "  when(boundp('schCreateWire)",
        "    errset(schCreateWire(cv \"draw\" \"full\" list(list(x1 y1) list(x2 y2)) 0.0625 0.0625 0.0) t)",
        "  )",
        ")",
        "",
        "let((libName cellName cv master inst net)",
        f"  libName = {_skill_str(lib_name)}",
        f"  cellName = {_skill_str(cell_name)}",
        "  unless(ddGetObj(libName) ddCreateLib(libName))",
        "  cv = dbOpenCellViewByType(libName cellName \"schematic\" \"schematic\" \"w\")",
        "  unless(cv error(\"Unable to open target schematic %s/%s\\n\" libName cellName))",
        "  boClearCellView(cv)",
        "",
        "  ;; Create nets",
    ]

    for net_name in ir.nets:
        lines.append(f"  boEnsureNet(cv {_skill_str(net_name)})")

    lines.extend(["", "  ;; Create top-level terminals"])
    for index, port in enumerate(ir.ports):
        direction = _port_direction(port)
        x1, y1, x2, y2 = _port_stub(index)
        lines.append(f"  net = boEnsureNet(cv {_skill_str(port)})")
        lines.append(f"  dbCreateTerm(net {_skill_str(port)} {_skill_str(direction)})")
        lines.append(f"  boMaybeCreateWire(cv {x1} {y1} {x2} {y2})")

    lines.extend(["", "  ;; Create and connect instances"])
    for inst_obj in ir.instances:
        lines.extend(_instance_lines(inst_obj, device_map, placements[inst_obj.name]))

    lines.extend(
        [
            "",
            "  schCheck(cv)",
            "  dbSave(cv)",
            "  printf(\"BO schematic generated: %s/%s/schematic\\n\" libName cellName)",
            "  cv",
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def _validate_device_map(ir: SchematicIR, device_map: DeviceMap) -> None:
    missing = sorted({inst.model for inst in ir.instances if inst.model not in device_map})
    if missing:
        raise ValueError(
            "Device map is missing entries for models/kinds: " + ", ".join(missing)
        )


def _instance_lines(
    inst: Instance,
    device_map: DeviceMap,
    placement: Placement,
) -> list[str]:
    entry = device_map[inst.model]
    lines = [
        f"  master = dbOpenCellViewByType({_skill_str(entry.lib)} {_skill_str(entry.cell)} {_skill_str(entry.view)} \"\" \"r\")",
        f"  unless(master error(\"Unable to open master {entry.lib}/{entry.cell}/{entry.view}\\n\"))",
        (
            f"  inst = dbCreateInst(cv master {_skill_str(inst.name)} "
            f"list({placement.x} {placement.y}) {_skill_str(placement.orient)})"
        ),
    ]

    for spice_param, value in inst.params.items():
        skill_param = entry.param_map.get(spice_param, spice_param.lower())
        lines.append(f"  boReplaceProp(inst {_skill_str(skill_param)} {_skill_str(value)})")

    term_order = _term_order(inst, entry.term_order)
    for node, term_name in zip(inst.nodes, term_order):
        lines.append(f"  dbCreateConnByName(boEnsureNet(cv {_skill_str(node)}) inst {_skill_str(term_name)})")

    lines.append("")
    return lines


def _term_order(inst: Instance, configured: list[str]) -> list[str]:
    if configured:
        return configured
    if inst.kind == "mos":
        return ["D", "G", "S", "B"]
    return ["PLUS", "MINUS"]


def _port_direction(port: str) -> str:
    lower = port.lower()
    if lower in {"vout", "out"}:
        return "output"
    if lower in {"vdd", "vss", "gnd", "gnd!", "vdd!", "vss!"}:
        return "inputOutput"
    return "input"


def _port_stub(index: int) -> tuple[int, int, int, int]:
    y = 750 - index * 140
    return (-1300, y, -1100, y)


def _skill_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
    return f"\"{escaped}\""
