"""Generate a read-only Virtuoso SKILL probe for one configured passive PCell."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from pdk_profiles import get_pdk_profile


@dataclass(frozen=True)
class ProbeTarget:
    virtuoso_lib: str
    virtuoso_cell: str
    virtuoso_view: str


def _resolve_probe_target(profile, device_name: str) -> ProbeTarget:
    device = profile.passive_devices.get(device_name)
    if device is not None:
        return ProbeTarget(
            virtuoso_lib=device.virtuoso_lib,
            virtuoso_cell=device.virtuoso_cell,
            virtuoso_view=device.virtuoso_view,
        )

    catalog_entry = profile.passive_device_catalog.get(device_name)
    if catalog_entry is not None:
        cells = catalog_entry.get("virtuoso_cells") or []
        if cells:
            return ProbeTarget(
                virtuoso_lib=profile.virtuoso_tech_lib,
                virtuoso_cell=str(cells[0]),
                virtuoso_view=str(catalog_entry.get("virtuoso_view") or "symbol"),
            )

    available = sorted(set(profile.passive_devices) | set(profile.passive_device_catalog))
    raise ValueError(
        f"Unknown passive device '{device_name}' "
        f"(available: {', '.join(available) or 'none'})"
    )


def render_cdf_probe(device_name: str, report_path: str = "passive_cdf_report.txt") -> str:
    profile = get_pdk_profile()
    target = _resolve_probe_target(profile, device_name)
    escaped_lib = _skill_escape(target.virtuoso_lib)
    escaped_cell = _skill_escape(target.virtuoso_cell)
    escaped_view = _skill_escape(target.virtuoso_view)
    escaped_report = _skill_escape(report_path)
    return f'''/* Read-only CDF/terminal probe generated by Circuit Agent. */
let((cellObj cdfObj master out)
  out = outfile("{escaped_report}" "w")
  cellObj = ddGetObj("{escaped_lib}" "{escaped_cell}")
  unless(cellObj error("PCell not found: {escaped_lib}/{escaped_cell}\\n"))
  fprintf(out "library\\t%s\\ncell\\t%s\\n" cellObj~>lib~>name cellObj~>name)
  cdfObj = cdfGetBaseCellCDF(cellObj)
  if(cdfObj then
    foreach(param cdfObj~>parameters
      fprintf(out "cdf\\t%s\\t%L\\t%L\\t%L\\t%L\\t%L\\t%L\\t%L\\t%L\\n"
        param~>name param~>type param~>defValue param~>units param~>prompt
        param~>choices param~>minVal param~>maxVal param~>callback)
    )
  else
    fprintf(out "warning\\tno base CDF\\n")
  )
  fprintf(out "simInfo\\t%L\\n" cdfObj~>simInfo)
  master = dbOpenCellViewByType("{escaped_lib}"
    "{escaped_cell}" "{escaped_view}" "" "r")
  when(master
    foreach(term master~>terminals fprintf(out "terminal\\t%s\\n" term~>name))
    dbClose(master)
  )
  close(out)
  printf("Passive CDF report written: {escaped_report}\\n")
)
exit()
'''


def _skill_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate read-only SKILL that reports a passive PCell CDF"
    )
    parser.add_argument(
        "--device",
        required=True,
        help="passive_devices or passive_device_catalog key",
    )
    parser.add_argument("--out", required=True, help="Generated .il file")
    parser.add_argument(
        "--report",
        default="passive_cdf_report.txt",
        help="Report path used when the generated SKILL runs in Virtuoso",
    )
    args = parser.parse_args()
    path = Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_cdf_probe(args.device, args.report), encoding="utf-8")
    print(f"CDF probe: {path}")


if __name__ == "__main__":
    main()
